spring.config.import=optional:file:.env[.properties]
spring.application.name=Contacts
spring.security.user.name=sujal
spring.security.user.password=sujal
spring.datasource.url=jdbc:postgresql://localhost:5432/Contacts
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
server.port=${PORT:8080}
